# Generated by Django 3.1.2 on 2022-08-14 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220814_1643'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriaCliente',
            new_name='Categoria',
        ),
    ]
