# Generated by Django 3.1.2 on 2022-08-14 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220814_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='categoria_cliente',
        ),
    ]
