# Generated by Django 3.1.2 on 2022-08-14 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_boleta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='CategoriaCli',
        ),
    ]
