# Generated by Django 3.1.2 on 2022-08-14 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220814_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriacli',
            old_name='nombre_categoria',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='cliente',
            name='categoria_cliente',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='core.categoriacli'),
            preserve_default=False,
        ),
    ]
