# Generated by Django 3.1.2 on 2022-08-15 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_auto_20220814_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_nombre', models.CharField(max_length=50)),
                ('p_apellido', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=8)),
                ('password2', models.CharField(max_length=8)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriacli')),
            ],
        ),
    ]
