# Generated by Django 3.1.2 on 2022-08-15 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220814_2207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoriaCli',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
